/* Generated by the Nim Compiler v0.20.99 */
/*   (c) 2019 Andreas Rumpf */

var framePtr = null;
var excHandler = 0;
var lastJSError = null;
if (typeof Int8Array === 'undefined') Int8Array = Array;
if (typeof Int16Array === 'undefined') Int16Array = Array;
if (typeof Int32Array === 'undefined') Int32Array = Array;
if (typeof Uint8Array === 'undefined') Uint8Array = Array;
if (typeof Uint16Array === 'undefined') Uint16Array = Array;
if (typeof Uint32Array === 'undefined') Uint32Array = Array;
if (typeof Float32Array === 'undefined') Float32Array = Array;
if (typeof Float64Array === 'undefined') Float64Array = Array;
var NTI45032 = {size: 0,kind: 1,base: null,node: null,finalizer: null};
var NTI207074 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI48862 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI209566 = {size: 0,kind: 24,base: null,node: null,finalizer: null};
var NTI87448 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI87444 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI87440 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI87436 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI87432 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI87428 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI87424 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI87420 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI87416 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI87412 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI87408 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI87404 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI87400 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI87396 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI87392 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI87388 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI87384 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI87380 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI87376 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI87372 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI87205 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI87283 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI87281 = {size: 0,kind: 22,base: null,node: null,finalizer: null};
var NTI87227 = {size: 0, kind: 14, base: null, node: null, finalizer: null};
var NTI87565 = {size: 0,kind: 24,base: null,node: null,finalizer: null};
var NTI87563 = {size: 0,kind: 24,base: null,node: null,finalizer: null};
var NTI87561 = {size: 0,kind: 24,base: null,node: null,finalizer: null};
var NTI87231 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI87229 = {size: 0,kind: 22,base: null,node: null,finalizer: null};
var NTI89305 = {size: 0,kind: 24,base: null,node: null,finalizer: null};
var NTI48850 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI48858 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI45006 = {size: 0,kind: 31,base: null,node: null,finalizer: null};
var NTI66156 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI48808 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI48914 = {size: 0,kind: 22,base: null,node: null,finalizer: null};
var NTI45016 = {size: 0,kind: 40,base: null,node: null,finalizer: null};
var NTI45040 = {size: 0,kind: 28,base: null,node: null,finalizer: null};
var NTI45042 = {size: 0,kind: 29,base: null,node: null,finalizer: null};
var NTI48908 = {size: 0,kind: 22,base: null,node: null,finalizer: null};
var NTI48826 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI48828 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI48842 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI48846 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NNI48846 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI48846.node = NNI48846;
var NNI48842 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI48842.node = NNI48842;
var NNI48828 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI48828.node = NNI48828;
NTI48908.base = NTI48826;
NTI48914.base = NTI48826;
var NNI48826 = {kind: 2, len: 6, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "parent", len: 0, typ: NTI48908, name: "parent", sons: null}, 
{kind: 1, offset: "name", len: 0, typ: NTI45042, name: "name", sons: null}, 
{kind: 1, offset: "message", len: 0, typ: NTI45040, name: "msg", sons: null}, 
{kind: 1, offset: "trace", len: 0, typ: NTI45040, name: "trace", sons: null}, 
{kind: 1, offset: "raiseId", len: 0, typ: NTI45016, name: "raiseId", sons: null}, 
{kind: 1, offset: "up", len: 0, typ: NTI48914, name: "up", sons: null}]};
NTI48826.node = NNI48826;
var NNI48808 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI48808.node = NNI48808;
NTI48826.base = NTI48808;
NTI48828.base = NTI48826;
NTI48842.base = NTI48828;
NTI48846.base = NTI48842;
var NNI66156 = {kind: 2, len: 2, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "Field0", len: 0, typ: NTI45042, name: "Field0", sons: null}, 
{kind: 1, offset: "Field1", len: 0, typ: NTI45006, name: "Field1", sons: null}]};
NTI66156.node = NNI66156;
var NNI48858 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI48858.node = NNI48858;
NTI48858.base = NTI48828;
var NNI48850 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI48850.node = NNI48850;
NTI48850.base = NTI48828;
NTI87561.base = NTI87229;
NTI87563.base = NTI87229;
NTI87565.base = NTI87229;
var NNI87227 = {kind: 2, offset: 0, typ: null, name: null, len: 12, sons: {"1": {kind: 1, offset: 1, typ: NTI87227, name: "ElementNode", len: 0, sons: null}, 
"2": {kind: 1, offset: 2, typ: NTI87227, name: "AttributeNode", len: 0, sons: null}, 
"3": {kind: 1, offset: 3, typ: NTI87227, name: "TextNode", len: 0, sons: null}, 
"4": {kind: 1, offset: 4, typ: NTI87227, name: "CDATANode", len: 0, sons: null}, 
"5": {kind: 1, offset: 5, typ: NTI87227, name: "EntityRefNode", len: 0, sons: null}, 
"6": {kind: 1, offset: 6, typ: NTI87227, name: "EntityNode", len: 0, sons: null}, 
"7": {kind: 1, offset: 7, typ: NTI87227, name: "ProcessingInstructionNode", len: 0, sons: null}, 
"8": {kind: 1, offset: 8, typ: NTI87227, name: "CommentNode", len: 0, sons: null}, 
"9": {kind: 1, offset: 9, typ: NTI87227, name: "DocumentNode", len: 0, sons: null}, 
"10": {kind: 1, offset: 10, typ: NTI87227, name: "DocumentTypeNode", len: 0, sons: null}, 
"11": {kind: 1, offset: 11, typ: NTI87227, name: "DocumentFragmentNode", len: 0, sons: null}, 
"12": {kind: 1, offset: 12, typ: NTI87227, name: "NotationNode", len: 0, sons: null}}};
NTI87227.node = NNI87227;
var NNI87283 = {kind: 2, len: 92, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "background", len: 0, typ: NTI45042, name: "background", sons: null}, 
{kind: 1, offset: "backgroundAttachment", len: 0, typ: NTI45042, name: "backgroundAttachment", sons: null}, 
{kind: 1, offset: "backgroundColor", len: 0, typ: NTI45042, name: "backgroundColor", sons: null}, 
{kind: 1, offset: "backgroundImage", len: 0, typ: NTI45042, name: "backgroundImage", sons: null}, 
{kind: 1, offset: "backgroundPosition", len: 0, typ: NTI45042, name: "backgroundPosition", sons: null}, 
{kind: 1, offset: "backgroundRepeat", len: 0, typ: NTI45042, name: "backgroundRepeat", sons: null}, 
{kind: 1, offset: "border", len: 0, typ: NTI45042, name: "border", sons: null}, 
{kind: 1, offset: "borderBottom", len: 0, typ: NTI45042, name: "borderBottom", sons: null}, 
{kind: 1, offset: "borderBottomColor", len: 0, typ: NTI45042, name: "borderBottomColor", sons: null}, 
{kind: 1, offset: "borderBottomStyle", len: 0, typ: NTI45042, name: "borderBottomStyle", sons: null}, 
{kind: 1, offset: "borderBottomWidth", len: 0, typ: NTI45042, name: "borderBottomWidth", sons: null}, 
{kind: 1, offset: "borderColor", len: 0, typ: NTI45042, name: "borderColor", sons: null}, 
{kind: 1, offset: "borderLeft", len: 0, typ: NTI45042, name: "borderLeft", sons: null}, 
{kind: 1, offset: "borderLeftColor", len: 0, typ: NTI45042, name: "borderLeftColor", sons: null}, 
{kind: 1, offset: "borderLeftStyle", len: 0, typ: NTI45042, name: "borderLeftStyle", sons: null}, 
{kind: 1, offset: "borderLeftWidth", len: 0, typ: NTI45042, name: "borderLeftWidth", sons: null}, 
{kind: 1, offset: "borderRight", len: 0, typ: NTI45042, name: "borderRight", sons: null}, 
{kind: 1, offset: "borderRightColor", len: 0, typ: NTI45042, name: "borderRightColor", sons: null}, 
{kind: 1, offset: "borderRightStyle", len: 0, typ: NTI45042, name: "borderRightStyle", sons: null}, 
{kind: 1, offset: "borderRightWidth", len: 0, typ: NTI45042, name: "borderRightWidth", sons: null}, 
{kind: 1, offset: "borderStyle", len: 0, typ: NTI45042, name: "borderStyle", sons: null}, 
{kind: 1, offset: "borderTop", len: 0, typ: NTI45042, name: "borderTop", sons: null}, 
{kind: 1, offset: "borderTopColor", len: 0, typ: NTI45042, name: "borderTopColor", sons: null}, 
{kind: 1, offset: "borderTopStyle", len: 0, typ: NTI45042, name: "borderTopStyle", sons: null}, 
{kind: 1, offset: "borderTopWidth", len: 0, typ: NTI45042, name: "borderTopWidth", sons: null}, 
{kind: 1, offset: "borderWidth", len: 0, typ: NTI45042, name: "borderWidth", sons: null}, 
{kind: 1, offset: "bottom", len: 0, typ: NTI45042, name: "bottom", sons: null}, 
{kind: 1, offset: "captionSide", len: 0, typ: NTI45042, name: "captionSide", sons: null}, 
{kind: 1, offset: "clear", len: 0, typ: NTI45042, name: "clear", sons: null}, 
{kind: 1, offset: "clip", len: 0, typ: NTI45042, name: "clip", sons: null}, 
{kind: 1, offset: "color", len: 0, typ: NTI45042, name: "color", sons: null}, 
{kind: 1, offset: "cursor", len: 0, typ: NTI45042, name: "cursor", sons: null}, 
{kind: 1, offset: "direction", len: 0, typ: NTI45042, name: "direction", sons: null}, 
{kind: 1, offset: "display", len: 0, typ: NTI45042, name: "display", sons: null}, 
{kind: 1, offset: "emptyCells", len: 0, typ: NTI45042, name: "emptyCells", sons: null}, 
{kind: 1, offset: "cssFloat", len: 0, typ: NTI45042, name: "cssFloat", sons: null}, 
{kind: 1, offset: "font", len: 0, typ: NTI45042, name: "font", sons: null}, 
{kind: 1, offset: "fontFamily", len: 0, typ: NTI45042, name: "fontFamily", sons: null}, 
{kind: 1, offset: "fontSize", len: 0, typ: NTI45042, name: "fontSize", sons: null}, 
{kind: 1, offset: "fontStretch", len: 0, typ: NTI45042, name: "fontStretch", sons: null}, 
{kind: 1, offset: "fontStyle", len: 0, typ: NTI45042, name: "fontStyle", sons: null}, 
{kind: 1, offset: "fontVariant", len: 0, typ: NTI45042, name: "fontVariant", sons: null}, 
{kind: 1, offset: "fontWeight", len: 0, typ: NTI45042, name: "fontWeight", sons: null}, 
{kind: 1, offset: "height", len: 0, typ: NTI45042, name: "height", sons: null}, 
{kind: 1, offset: "left", len: 0, typ: NTI45042, name: "left", sons: null}, 
{kind: 1, offset: "letterSpacing", len: 0, typ: NTI45042, name: "letterSpacing", sons: null}, 
{kind: 1, offset: "lineHeight", len: 0, typ: NTI45042, name: "lineHeight", sons: null}, 
{kind: 1, offset: "listStyle", len: 0, typ: NTI45042, name: "listStyle", sons: null}, 
{kind: 1, offset: "listStyleImage", len: 0, typ: NTI45042, name: "listStyleImage", sons: null}, 
{kind: 1, offset: "listStylePosition", len: 0, typ: NTI45042, name: "listStylePosition", sons: null}, 
{kind: 1, offset: "listStyleType", len: 0, typ: NTI45042, name: "listStyleType", sons: null}, 
{kind: 1, offset: "margin", len: 0, typ: NTI45042, name: "margin", sons: null}, 
{kind: 1, offset: "marginBottom", len: 0, typ: NTI45042, name: "marginBottom", sons: null}, 
{kind: 1, offset: "marginLeft", len: 0, typ: NTI45042, name: "marginLeft", sons: null}, 
{kind: 1, offset: "marginRight", len: 0, typ: NTI45042, name: "marginRight", sons: null}, 
{kind: 1, offset: "marginTop", len: 0, typ: NTI45042, name: "marginTop", sons: null}, 
{kind: 1, offset: "maxHeight", len: 0, typ: NTI45042, name: "maxHeight", sons: null}, 
{kind: 1, offset: "maxWidth", len: 0, typ: NTI45042, name: "maxWidth", sons: null}, 
{kind: 1, offset: "minHeight", len: 0, typ: NTI45042, name: "minHeight", sons: null}, 
{kind: 1, offset: "minWidth", len: 0, typ: NTI45042, name: "minWidth", sons: null}, 
{kind: 1, offset: "opacity", len: 0, typ: NTI45042, name: "opacity", sons: null}, 
{kind: 1, offset: "overflow", len: 0, typ: NTI45042, name: "overflow", sons: null}, 
{kind: 1, offset: "padding", len: 0, typ: NTI45042, name: "padding", sons: null}, 
{kind: 1, offset: "paddingBottom", len: 0, typ: NTI45042, name: "paddingBottom", sons: null}, 
{kind: 1, offset: "paddingLeft", len: 0, typ: NTI45042, name: "paddingLeft", sons: null}, 
{kind: 1, offset: "paddingRight", len: 0, typ: NTI45042, name: "paddingRight", sons: null}, 
{kind: 1, offset: "paddingTop", len: 0, typ: NTI45042, name: "paddingTop", sons: null}, 
{kind: 1, offset: "pageBreakAfter", len: 0, typ: NTI45042, name: "pageBreakAfter", sons: null}, 
{kind: 1, offset: "pageBreakBefore", len: 0, typ: NTI45042, name: "pageBreakBefore", sons: null}, 
{kind: 1, offset: "pointerEvents", len: 0, typ: NTI45042, name: "pointerEvents", sons: null}, 
{kind: 1, offset: "position", len: 0, typ: NTI45042, name: "position", sons: null}, 
{kind: 1, offset: "right", len: 0, typ: NTI45042, name: "right", sons: null}, 
{kind: 1, offset: "scrollbar3dLightColor", len: 0, typ: NTI45042, name: "scrollbar3dLightColor", sons: null}, 
{kind: 1, offset: "scrollbarArrowColor", len: 0, typ: NTI45042, name: "scrollbarArrowColor", sons: null}, 
{kind: 1, offset: "scrollbarBaseColor", len: 0, typ: NTI45042, name: "scrollbarBaseColor", sons: null}, 
{kind: 1, offset: "scrollbarDarkshadowColor", len: 0, typ: NTI45042, name: "scrollbarDarkshadowColor", sons: null}, 
{kind: 1, offset: "scrollbarFaceColor", len: 0, typ: NTI45042, name: "scrollbarFaceColor", sons: null}, 
{kind: 1, offset: "scrollbarHighlightColor", len: 0, typ: NTI45042, name: "scrollbarHighlightColor", sons: null}, 
{kind: 1, offset: "scrollbarShadowColor", len: 0, typ: NTI45042, name: "scrollbarShadowColor", sons: null}, 
{kind: 1, offset: "scrollbarTrackColor", len: 0, typ: NTI45042, name: "scrollbarTrackColor", sons: null}, 
{kind: 1, offset: "tableLayout", len: 0, typ: NTI45042, name: "tableLayout", sons: null}, 
{kind: 1, offset: "textAlign", len: 0, typ: NTI45042, name: "textAlign", sons: null}, 
{kind: 1, offset: "textDecoration", len: 0, typ: NTI45042, name: "textDecoration", sons: null}, 
{kind: 1, offset: "textIndent", len: 0, typ: NTI45042, name: "textIndent", sons: null}, 
{kind: 1, offset: "textTransform", len: 0, typ: NTI45042, name: "textTransform", sons: null}, 
{kind: 1, offset: "transform", len: 0, typ: NTI45042, name: "transform", sons: null}, 
{kind: 1, offset: "top", len: 0, typ: NTI45042, name: "top", sons: null}, 
{kind: 1, offset: "verticalAlign", len: 0, typ: NTI45042, name: "verticalAlign", sons: null}, 
{kind: 1, offset: "visibility", len: 0, typ: NTI45042, name: "visibility", sons: null}, 
{kind: 1, offset: "width", len: 0, typ: NTI45042, name: "width", sons: null}, 
{kind: 1, offset: "wordSpacing", len: 0, typ: NTI45042, name: "wordSpacing", sons: null}, 
{kind: 1, offset: "zIndex", len: 0, typ: NTI45006, name: "zIndex", sons: null}]};
NTI87283.node = NNI87283;
NTI87283.base = NTI48808;
NTI87281.base = NTI87283;
var NNI87231 = {kind: 2, len: 14, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "attributes", len: 0, typ: NTI87561, name: "attributes", sons: null}, 
{kind: 1, offset: "childNodes", len: 0, typ: NTI87563, name: "childNodes", sons: null}, 
{kind: 1, offset: "children", len: 0, typ: NTI87565, name: "children", sons: null}, 
{kind: 1, offset: "data", len: 0, typ: NTI45042, name: "data", sons: null}, 
{kind: 1, offset: "firstChild", len: 0, typ: NTI87229, name: "firstChild", sons: null}, 
{kind: 1, offset: "lastChild", len: 0, typ: NTI87229, name: "lastChild", sons: null}, 
{kind: 1, offset: "nextSibling", len: 0, typ: NTI87229, name: "nextSibling", sons: null}, 
{kind: 1, offset: "nodeName", len: 0, typ: NTI45042, name: "nodeName", sons: null}, 
{kind: 1, offset: "nodeType", len: 0, typ: NTI87227, name: "nodeType", sons: null}, 
{kind: 1, offset: "nodeValue", len: 0, typ: NTI45042, name: "nodeValue", sons: null}, 
{kind: 1, offset: "parentNode", len: 0, typ: NTI87229, name: "parentNode", sons: null}, 
{kind: 1, offset: "previousSibling", len: 0, typ: NTI87229, name: "previousSibling", sons: null}, 
{kind: 1, offset: "innerHTML", len: 0, typ: NTI45042, name: "innerHTML", sons: null}, 
{kind: 1, offset: "style", len: 0, typ: NTI87281, name: "style", sons: null}]};
NTI87231.node = NNI87231;
var NNI87205 = {kind: 2, len: 20, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "onabort", len: 0, typ: NTI87372, name: "onabort", sons: null}, 
{kind: 1, offset: "onblur", len: 0, typ: NTI87376, name: "onblur", sons: null}, 
{kind: 1, offset: "onchange", len: 0, typ: NTI87380, name: "onchange", sons: null}, 
{kind: 1, offset: "onclick", len: 0, typ: NTI87384, name: "onclick", sons: null}, 
{kind: 1, offset: "ondblclick", len: 0, typ: NTI87388, name: "ondblclick", sons: null}, 
{kind: 1, offset: "onerror", len: 0, typ: NTI87392, name: "onerror", sons: null}, 
{kind: 1, offset: "onfocus", len: 0, typ: NTI87396, name: "onfocus", sons: null}, 
{kind: 1, offset: "onkeydown", len: 0, typ: NTI87400, name: "onkeydown", sons: null}, 
{kind: 1, offset: "onkeypress", len: 0, typ: NTI87404, name: "onkeypress", sons: null}, 
{kind: 1, offset: "onkeyup", len: 0, typ: NTI87408, name: "onkeyup", sons: null}, 
{kind: 1, offset: "onload", len: 0, typ: NTI87412, name: "onload", sons: null}, 
{kind: 1, offset: "onmousedown", len: 0, typ: NTI87416, name: "onmousedown", sons: null}, 
{kind: 1, offset: "onmousemove", len: 0, typ: NTI87420, name: "onmousemove", sons: null}, 
{kind: 1, offset: "onmouseout", len: 0, typ: NTI87424, name: "onmouseout", sons: null}, 
{kind: 1, offset: "onmouseover", len: 0, typ: NTI87428, name: "onmouseover", sons: null}, 
{kind: 1, offset: "onmouseup", len: 0, typ: NTI87432, name: "onmouseup", sons: null}, 
{kind: 1, offset: "onreset", len: 0, typ: NTI87436, name: "onreset", sons: null}, 
{kind: 1, offset: "onselect", len: 0, typ: NTI87440, name: "onselect", sons: null}, 
{kind: 1, offset: "onsubmit", len: 0, typ: NTI87444, name: "onsubmit", sons: null}, 
{kind: 1, offset: "onunload", len: 0, typ: NTI87448, name: "onunload", sons: null}]};
NTI87205.node = NNI87205;
NTI87205.base = NTI48808;
NTI87231.base = NTI87205;
NTI87229.base = NTI87231;
NTI89305.base = NTI87229;
NTI209566.base = NTI45042;
var NNI48862 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI48862.node = NNI48862;
NTI48862.base = NTI48828;
var NNI207074 = {kind: 2, len: 2, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "Field0", len: 0, typ: NTI45006, name: "Field0", sons: null}, 
{kind: 1, offset: "Field1", len: 0, typ: NTI45032, name: "Field1", sons: null}]};
NTI207074.node = NNI207074;

function makeNimstrLit(c_68254) {
		  var ln = c_68254.length;
  var result = new Array(ln);
  for (var i = 0; i < ln; ++i) {
    result[i] = c_68254.charCodeAt(i);
  }
  return result;
  

	
}

function setConstr() {
		    var result = {};
    for (var i = 0; i < arguments.length; ++i) {
      var x = arguments[i];
      if (typeof(x) == "object") {
        for (var j = x[0]; j <= x[1]; ++j) {
          result[j] = true;
        }
      } else {
        result[x] = true;
      }
    }
    return result;
  

	
}
var ConstSet1 = setConstr(17, 16, 4, 18, 27, 19, 23, 22, 21);

function nimCopy(dest_69627, src_69628, ti_69629) {
	var result_69819 = null;

		switch (ti_69629.kind) {
		case 21:
		case 22:
		case 23:
		case 5:
			if (!(is_fat_pointer_69601(ti_69629))) {
			result_69819 = src_69628;
			}
			else {
				result_69819 = [src_69628[0], src_69628[1]];
			}
			
			break;
		case 19:
			      if (dest_69627 === null || dest_69627 === undefined) {
        dest_69627 = {};
      }
      else {
        for (var key in dest_69627) { delete dest_69627[key]; }
      }
      for (var key in src_69628) { dest_69627[key] = src_69628[key]; }
      result_69819 = dest_69627;
    
			break;
		case 18:
		case 17:
			if (!((ti_69629.base == null))) {
			result_69819 = nimCopy(dest_69627, src_69628, ti_69629.base);
			}
			else {
			if ((ti_69629.kind == 17)) {
			result_69819 = (dest_69627 === null || dest_69627 === undefined) ? {m_type: ti_69629} : dest_69627;
			}
			else {
				result_69819 = (dest_69627 === null || dest_69627 === undefined) ? {} : dest_69627;
			}
			}
			nimCopyAux(result_69819, src_69628, ti_69629.node);
			break;
		case 24:
		case 4:
		case 27:
		case 16:
			      if (src_69628 === null) {
        result_69819 = null;
      }
      else {
        if (dest_69627 === null || dest_69627 === undefined) {
          dest_69627 = new Array(src_69628.length);
        }
        else {
          dest_69627.length = src_69628.length;
        }
        result_69819 = dest_69627;
        for (var i = 0; i < src_69628.length; ++i) {
          result_69819[i] = nimCopy(result_69819[i], src_69628[i], ti_69629.base);
        }
      }
    
			break;
		case 28:
			      if (src_69628 !== null) {
        result_69819 = src_69628.slice(0);
      }
    
			break;
		default: 
			result_69819 = src_69628;
			break;
		}

	return result_69819;

}

function arrayConstr(len_69886, value_69887, typ_69888) {
		    var result = new Array(len_69886);
    for (var i = 0; i < len_69886; ++i) result[i] = nimCopy(null, value_69887, typ_69888);
    return result;
  

	
}

function cstrToNimstr(c_68271) {
		  var ln = c_68271.length;
  var result = new Array(ln);
  var r = 0;
  for (var i = 0; i < ln; ++i) {
    var ch = c_68271.charCodeAt(i);

    if (ch < 128) {
      result[r] = ch;
    }
    else {
      if (ch < 2048) {
        result[r] = (ch >> 6) | 192;
      }
      else {
        if (ch < 55296 || ch >= 57344) {
          result[r] = (ch >> 12) | 224;
        }
        else {
            ++i;
            ch = 65536 + (((ch & 1023) << 10) | (c_68271.charCodeAt(i) & 1023));
            result[r] = (ch >> 18) | 240;
            ++r;
            result[r] = ((ch >> 12) & 63) | 128;
        }
        ++r;
        result[r] = ((ch >> 6) & 63) | 128;
      }
      ++r;
      result[r] = (ch & 63) | 128;
    }
    ++r;
  }
  return result;
  

	
}

function toJSStr(s_68288) {
										var Tmp5;
						var Tmp7;

	var result_68289 = null;

		var res_68347 = new_seq_68320((s_68288 != null ? s_68288.length : 0));
		var i_68349 = 0;
		var j_68351 = 0;
		L1: do {
				L2: while (true) {
				if (!(i_68349 < (s_68288 != null ? s_68288.length : 0))) break L2;
					var c_68352 = s_68288[i_68349];
					if ((c_68352 < 128)) {
					res_68347[j_68351] = String.fromCharCode(c_68352);
					i_68349 += 1;
					}
					else {
						var helper_68375 = new_seq_68320(0);
						L3: do {
								L4: while (true) {
								if (!true) break L4;
									var code_68376 = c_68352.toString(16);
									if (((code_68376 != null ? code_68376.length : 0) == 1)) {
									if (helper_68375 != null) { helper_68375.push("%0"); } else { helper_68375 = ["%0"]; };
									}
									else {
									if (helper_68375 != null) { helper_68375.push("%"); } else { helper_68375 = ["%"]; };
									}
									
									if (helper_68375 != null) { helper_68375.push(code_68376); } else { helper_68375 = [code_68376]; };
									i_68349 += 1;
										if (((s_68288 != null ? s_68288.length : 0) <= i_68349)) Tmp5 = true; else {											Tmp5 = (s_68288[i_68349] < 128);										}									if (Tmp5) {
									break L3;
									}
									
									c_68352 = s_68288[i_68349];
								}
						} while(false);
++excHandler;
						Tmp7 = framePtr;
						try {
						res_68347[j_68351] = decodeURIComponent(helper_68375.join(""));
--excHandler;
} catch (EXC) {
 var prevJSError = lastJSError;
 lastJSError = EXC;
 --excHandler;
						framePtr = Tmp7;
						res_68347[j_68351] = helper_68375.join("");
						lastJSError = prevJSError;
						} finally {
						framePtr = Tmp7;
						}
					}
					
					j_68351 += 1;
				}
		} while(false);
		if (res_68347 === null) res_68347 = [];
               if (res_68347.length < j_68351) { for (var i=res_68347.length;i<j_68351;++i) res_68347.push(null); }
               else { res_68347.length = j_68351; };
		result_68289 = res_68347.join("");

	return result_68289;

}

function raiseException(e_66618, ename_66619) {
		e_66618.name = ename_66619;
		if ((excHandler == 0)) {
		unhandledException(e_66618);
		}
		
		e_66618.trace = nimCopy(null, raw_write_stack_trace_66468(), NTI45040);
		throw e_66618;

	
}

function addInt(a_68803, b_68804) {
		    var result = a_68803 + b_68804;
    if (result > 2147483647 || result < -2147483648) raiseOverflow();
    return result;
  

	
}

function chckIndx(i_69905, a_69906, b_69907) {
			var Tmp1;

	var result_69908 = 0;

	BeforeRet: do {
			if (!(a_69906 <= i_69905)) Tmp1 = false; else {				Tmp1 = (i_69905 <= b_69907);			}		if (Tmp1) {
		result_69908 = i_69905;
		break BeforeRet;
		}
		else {
		raiseIndexError(i_69905, a_69906, b_69907);
		}
		
	} while (false);

	return result_69908;

}

function subInt(a_68821, b_68822) {
		    var result = a_68821 - b_68822;
    if (result > 2147483647 || result < -2147483648) raiseOverflow();
    return result;
  

	
}
var ConstSet2 = setConstr([65, 90]);

function chckRange(i_69924, a_69925, b_69926) {
			var Tmp1;

	var result_69927 = 0;

	BeforeRet: do {
			if (!(a_69925 <= i_69924)) Tmp1 = false; else {				Tmp1 = (i_69924 <= b_69926);			}		if (Tmp1) {
		result_69927 = i_69924;
		break BeforeRet;
		}
		else {
		raiseRangeError();
		}
		
	} while (false);

	return result_69927;

}
var ConstSet3 = setConstr(95, 32, 46);
var ConstSet4 = setConstr(95, 32, 46);

function mulInt(a_68839, b_68840) {
		    var result = a_68839 * b_68840;
    if (result > 2147483647 || result < -2147483648) raiseOverflow();
    return result;
  

	
}
var ConstSet5 = setConstr([97, 122]);
var ConstSet6 = setConstr([65, 90], [97, 122]);
var ConstSet7 = setConstr([97, 122]);
var ConstSet8 = setConstr([65, 90]);

function nimMax(a_69221, b_69222) {
		var Tmp1;

	var result_69223 = 0;

	BeforeRet: do {
		if ((b_69222 <= a_69221)) {
		Tmp1 = a_69221;
		}
		else {
		Tmp1 = b_69222;
		}
		
		result_69223 = Tmp1;
		break BeforeRet;
	} while (false);

	return result_69223;

}

function nimMin(a_69203, b_69204) {
		var Tmp1;

	var result_69205 = 0;

	BeforeRet: do {
		if ((a_69203 <= b_69204)) {
		Tmp1 = a_69203;
		}
		else {
		Tmp1 = b_69204;
		}
		
		result_69205 = Tmp1;
		break BeforeRet;
	} while (false);

	return result_69205;

}
var nim_program_result = 0;
var global_raise_hook_63618 = [null];
var local_raise_hook_63623 = [null];
var out_of_mem_hook_63626 = [null];
  if (!Math.trunc) {
    Math.trunc = function(v) {
      v = +v;
      if (!isFinite(v)) return v;

      return (v - v % 1)   ||   (v < 0 ? -0 : v === 0 ? v : 0);
    };
  }
var alternative_209315 = [null];

function is_fat_pointer_69601(ti_69603) {
	var result_69604 = false;

	BeforeRet: do {
		result_69604 = !((ConstSet1[ti_69603.base.kind] != undefined));
		break BeforeRet;
	} while (false);

	return result_69604;

}

function nimCopyAux(dest_69632, src_69633, n_69635) {
		switch (n_69635.kind) {
		case 0:
			break;
		case 1:
			      dest_69632[n_69635.offset] = nimCopy(dest_69632[n_69635.offset], src_69633[n_69635.offset], n_69635.typ);
    
			break;
		case 2:
			    for (var i = 0; i < n_69635.sons.length; i++) {
      nimCopyAux(dest_69632, src_69633, n_69635.sons[i]);
    }
    
			break;
		case 3:
			      dest_69632[n_69635.offset] = nimCopy(dest_69632[n_69635.offset], src_69633[n_69635.offset], n_69635.typ);
      for (var i = 0; i < n_69635.sons.length; ++i) {
        nimCopyAux(dest_69632, src_69633, n_69635.sons[i][1]);
      }
    
			break;
		}

	
}

function add_63638(x_63641, x_63641_Idx, y_63642) {
		      if (x_63641[x_63641_Idx] === null) { x_63641[x_63641_Idx] = []; }
      var off = x_63641[x_63641_Idx].length;
      x_63641[x_63641_Idx].length += y_63642.length;
      for (var i = 0; i < y_63642.length; ++i) {
        x_63641[x_63641_Idx][off+i] = y_63642.charCodeAt(i);
      }
    

	
}

function aux_write_stack_trace_66151(f_66153) {
					var Tmp3;

	var result_66154 = [null];

		var it_66162 = f_66153;
		var i_66164 = 0;
		var total_66166 = 0;
		var temp_frames_66173 = arrayConstr(64, {Field0: null, Field1: 0}, NTI66156);
		L1: do {
				L2: while (true) {
					if (!!((it_66162 == null))) Tmp3 = false; else {						Tmp3 = (i_66164 <= 63);					}				if (!Tmp3) break L2;
					temp_frames_66173[i_66164].Field0 = it_66162.procname;
					temp_frames_66173[i_66164].Field1 = it_66162.line;
					i_66164 += 1;
					total_66166 += 1;
					it_66162 = it_66162.prev;
				}
		} while(false);
		L4: do {
				L5: while (true) {
				if (!!((it_66162 == null))) break L5;
					total_66166 += 1;
					it_66162 = it_66162.prev;
				}
		} while(false);
		result_66154[0] = nimCopy(null, [], NTI45040);
		if (!((total_66166 == i_66164))) {
		if (result_66154[0] != null) { result_66154[0] = (result_66154[0]).concat(makeNimstrLit("(")); } else { result_66154[0] = makeNimstrLit("("); };
		if (result_66154[0] != null) { result_66154[0] = (result_66154[0]).concat(cstrToNimstr(((total_66166 - i_66164))+"")); } else { result_66154[0] = cstrToNimstr(((total_66166 - i_66164))+"").slice(); };
		if (result_66154[0] != null) { result_66154[0] = (result_66154[0]).concat(makeNimstrLit(" calls omitted) ...\x0A")); } else { result_66154[0] = makeNimstrLit(" calls omitted) ...\x0A"); };
		}
		
		L6: do {
			var j_66421 = 0;
			var colontmp__209456 = 0;
			colontmp__209456 = (i_66164 - 1);
			var res_209461 = colontmp__209456;
			L7: do {
					L8: while (true) {
					if (!(0 <= res_209461)) break L8;
						j_66421 = res_209461;
						add_63638(result_66154, 0, temp_frames_66173[j_66421].Field0);
						if ((0 < temp_frames_66173[j_66421].Field1)) {
						if (result_66154[0] != null) { result_66154[0] = (result_66154[0]).concat(makeNimstrLit(", line: ")); } else { result_66154[0] = makeNimstrLit(", line: "); };
						if (result_66154[0] != null) { result_66154[0] = (result_66154[0]).concat(cstrToNimstr((temp_frames_66173[j_66421].Field1)+"")); } else { result_66154[0] = cstrToNimstr((temp_frames_66173[j_66421].Field1)+"").slice(); };
						}
						
						if (result_66154[0] != null) { result_66154[0] = (result_66154[0]).concat(makeNimstrLit("\x0A")); } else { result_66154[0] = makeNimstrLit("\x0A"); };
						res_209461 -= 1;
					}
			} while(false);
		} while(false);

	return result_66154[0];

}

function raw_write_stack_trace_66468() {
	var result_66470 = null;

		if (!((framePtr == null))) {
		result_66470 = nimCopy(null, (makeNimstrLit("Traceback (most recent call last)\x0A") || []).concat(aux_write_stack_trace_66151(framePtr) || []), NTI45040);
		}
		else {
			result_66470 = nimCopy(null, makeNimstrLit("No stack traceback available\x0A"), NTI45040);
		}
		

	return result_66470;

}

function new_seq_68320(len_68323) {
	var result_68325 = null;

	var F={procname:"newSeq.newSeq",prev:framePtr,filename:"system.nim",line:0};
	framePtr = F;
		F.line = 996;
		result_68325 = new Array(len_68323); for (var i=0;i<len_68323;++i) {result_68325[i]=null;}	framePtr = F.prev;

	return result_68325;

}

function unhandledException(e_66529) {
		var buf_66530 = [[]];
		if (!(((e_66529.message != null ? e_66529.message.length : 0) == 0))) {
		if (buf_66530[0] != null) { buf_66530[0] = (buf_66530[0]).concat(makeNimstrLit("Error: unhandled exception: ")); } else { buf_66530[0] = makeNimstrLit("Error: unhandled exception: "); };
		if (buf_66530[0] != null) { buf_66530[0] = (buf_66530[0]).concat(e_66529.message); } else { buf_66530[0] = e_66529.message.slice(); };
		}
		else {
		if (buf_66530[0] != null) { buf_66530[0] = (buf_66530[0]).concat(makeNimstrLit("Error: unhandled exception")); } else { buf_66530[0] = makeNimstrLit("Error: unhandled exception"); };
		}
		
		if (buf_66530[0] != null) { buf_66530[0] = (buf_66530[0]).concat(makeNimstrLit(" [")); } else { buf_66530[0] = makeNimstrLit(" ["); };
		add_63638(buf_66530, 0, e_66529.name);
		if (buf_66530[0] != null) { buf_66530[0] = (buf_66530[0]).concat(makeNimstrLit("]\x0A")); } else { buf_66530[0] = makeNimstrLit("]\x0A"); };
		if (buf_66530[0] != null) { buf_66530[0] = (buf_66530[0]).concat(raw_write_stack_trace_66468()); } else { buf_66530[0] = raw_write_stack_trace_66468().slice(); };
		var cbuf_66601 = toJSStr(buf_66530[0]);
		framePtr = null;
		  if (typeof(Error) !== "undefined") {
    throw new Error(cbuf_66601);
  }
  else {
    throw cbuf_66601;
  }
  

	
}

function raiseOverflow() {
		var e_67042 = null;
		e_67042 = {m_type: NTI48846, parent: null, name: null, message: null, trace: null, raiseId: 0, up: null};
		e_67042.message = nimCopy(null, makeNimstrLit("over- or underflow"), NTI45040);
		e_67042.parent = null;
		raiseException(e_67042, "OverflowError");

	
}

function is_whitespace_208654(text_208656) {
		     return !/[^\s]/.test(text_208656);
  

	
}

function is_whitespace_208671(x_208673) {
		var Tmp1;
		var Tmp2;

	var result_208674 = false;

	var F={procname:"dochack.isWhitespace",prev:framePtr,filename:"dochack.nim",line:0};
	framePtr = F;
		F.line = 134;
		if (!(x_208673.nodeName == "#text")) Tmp2 = false; else {			Tmp2 = is_whitespace_208654(x_208673.textContent);		}		if (Tmp2) Tmp1 = true; else {			Tmp1 = (x_208673.nodeName == "#comment");		}		result_208674 = Tmp1;
	framePtr = F.prev;

	return result_208674;

}

function raiseIndexError(i_67639, a_67640, b_67641) {
		var Tmp1;

		var e_67802 = null;
		e_67802 = {m_type: NTI48858, parent: null, name: null, message: null, trace: null, raiseId: 0, up: null};
		if ((b_67641 < a_67640)) {
		Tmp1 = makeNimstrLit("index out of bounds, the container is empty");
		}
		else {
		Tmp1 = (makeNimstrLit("index ") || []).concat(cstrToNimstr((i_67639)+"") || [],makeNimstrLit(" not in ") || [],cstrToNimstr((a_67640)+"") || [],makeNimstrLit(" .. ") || [],cstrToNimstr((b_67641)+"") || []);
		}
		
		e_67802.message = nimCopy(null, Tmp1, NTI45040);
		e_67802.parent = null;
		raiseException(e_67802, "IndexError");

	
}

function to_toc_208688(x_208690, father_208691) {
								var Tmp5;
						var Tmp6;
						var Tmp7;
						var Tmp8;
			var Tmp15;

	var F={procname:"dochack.toToc",prev:framePtr,filename:"dochack.nim",line:0};
	framePtr = F;
		if ((x_208690.nodeName == "UL")) {
		F.line = 139;
		var f_208710 = {heading: null, kids: [], sortId: (father_208691.kids != null ? father_208691.kids.length : 0), doSort: false};
		F.line = 140;
		var i_208712 = 0;
		L1: do {
			F.line = 141;
				L2: while (true) {
				if (!(i_208712 < x_208690.childNodes.length)) break L2;
					F.line = 142;
					var nxt_208713 = addInt(i_208712, 1);
					L3: do {
						F.line = 143;
							L4: while (true) {
								if (!(nxt_208713 < x_208690.childNodes.length)) Tmp5 = false; else {									Tmp5 = is_whitespace_208671(x_208690.childNodes[nxt_208713]);								}							if (!Tmp5) break L4;
								F.line = 144;
								nxt_208713 = addInt(nxt_208713, 1);
							}
					} while(false);
						if (!(nxt_208713 < x_208690.childNodes.length)) Tmp8 = false; else {							Tmp8 = (x_208690.childNodes[i_208712].nodeName == "LI");						}						if (!Tmp8) Tmp7 = false; else {							Tmp7 = (x_208690.childNodes[i_208712].childNodes.length == 1);						}						if (!Tmp7) Tmp6 = false; else {							Tmp6 = (x_208690.childNodes[nxt_208713].nodeName == "UL");						}					if (Tmp6) {
					F.line = 147;
					var e_208738 = {heading: x_208690.childNodes[i_208712].childNodes[0], kids: [], sortId: (f_208710.kids != null ? f_208710.kids.length : 0), doSort: false};
					F.line = 148;
					var it_208739 = x_208690.childNodes[nxt_208713];
					L9: do {
						F.line = 149;
						var j_208747 = 0;
						F.line = 2728;
						var colontmp__209432 = 0;
						F.line = 149;
						colontmp__209432 = it_208739.childNodes.length;
						F.line = 2729;
						var i_209433 = 0;
						L10: do {
							F.line = 2730;
								L11: while (true) {
								if (!(i_209433 < colontmp__209432)) break L11;
									F.line = 149;
									j_208747 = i_209433;
									F.line = 150;
									to_toc_208688(it_208739.childNodes[j_208747], e_208738);
									F.line = 2732;
									i_209433 = addInt(i_209433, 1);
								}
						} while(false);
					} while(false);
					F.line = 151;
					if (f_208710.kids != null) { f_208710.kids.push(e_208738); } else { f_208710.kids = [e_208738]; };
					F.line = 152;
					i_208712 = addInt(nxt_208713, 1);
					}
					else {
						F.line = 154;
						to_toc_208688(x_208690.childNodes[i_208712], f_208710);
						F.line = 155;
						i_208712 = addInt(i_208712, 1);
					}
					
				}
		} while(false);
		F.line = 156;
		if (father_208691.kids != null) { father_208691.kids.push(f_208710); } else { father_208691.kids = [f_208710]; };
		}
		else {
		if (is_whitespace_208671(x_208690)) {
		}
		else {
		if ((x_208690.nodeName == "LI")) {
		F.line = 160;
		var idx_208782 = [];
		L12: do {
			F.line = 161;
			var i_208790 = 0;
			F.line = 2728;
			var colontmp__209437 = 0;
			F.line = 161;
			colontmp__209437 = x_208690.childNodes.length;
			F.line = 2729;
			var i_209438 = 0;
			L13: do {
				F.line = 2730;
					L14: while (true) {
					if (!(i_209438 < colontmp__209437)) break L14;
						F.line = 161;
						i_208790 = i_209438;
						if (!(is_whitespace_208671(x_208690.childNodes[i_208790]))) {
						F.line = 162;
						if (idx_208782 != null) { idx_208782.push(i_208790); } else { idx_208782 = [i_208790]; };
						}
						
						F.line = 2732;
						i_209438 = addInt(i_209438, 1);
					}
			} while(false);
		} while(false);
			if (!((idx_208782 != null ? idx_208782.length : 0) == 2)) Tmp15 = false; else {				Tmp15 = (x_208690.childNodes[idx_208782[chckIndx(1, 0, idx_208782.length+0-1)-0]].nodeName == "UL");			}		if (Tmp15) {
		F.line = 164;
		var e_208821 = {heading: x_208690.childNodes[idx_208782[chckIndx(0, 0, idx_208782.length+0-1)-0]], kids: [], sortId: (father_208691.kids != null ? father_208691.kids.length : 0), doSort: false};
		F.line = 166;
		var it_208822 = x_208690.childNodes[idx_208782[chckIndx(1, 0, idx_208782.length+0-1)-0]];
		L16: do {
			F.line = 167;
			var j_208830 = 0;
			F.line = 2728;
			var colontmp__209443 = 0;
			F.line = 167;
			colontmp__209443 = it_208822.childNodes.length;
			F.line = 2729;
			var i_209444 = 0;
			L17: do {
				F.line = 2730;
					L18: while (true) {
					if (!(i_209444 < colontmp__209443)) break L18;
						F.line = 167;
						j_208830 = i_209444;
						F.line = 168;
						to_toc_208688(it_208822.childNodes[j_208830], e_208821);
						F.line = 2732;
						i_209444 = addInt(i_209444, 1);
					}
			} while(false);
		} while(false);
		F.line = 169;
		if (father_208691.kids != null) { father_208691.kids.push(e_208821); } else { father_208691.kids = [e_208821]; };
		}
		else {
			L19: do {
				F.line = 171;
				var i_208845 = 0;
				F.line = 2728;
				var colontmp__209448 = 0;
				F.line = 171;
				colontmp__209448 = x_208690.childNodes.length;
				F.line = 2729;
				var i_209449 = 0;
				L20: do {
					F.line = 2730;
						L21: while (true) {
						if (!(i_209449 < colontmp__209448)) break L21;
							F.line = 171;
							i_208845 = i_209449;
							F.line = 172;
							to_toc_208688(x_208690.childNodes[i_208845], father_208691);
							F.line = 2732;
							i_209449 = addInt(i_209449, 1);
						}
				} while(false);
			} while(false);
		}
		
		}
		else {
			F.line = 174;
		if (father_208691.kids != null) { father_208691.kids.push({heading: x_208690, kids: [], sortId: (father_208691.kids != null ? father_208691.kids.length : 0), doSort: false}); } else { father_208691.kids = [{heading: x_208690, kids: [], sortId: (father_208691.kids != null ? father_208691.kids.length : 0), doSort: false}]; };
		}
		}}
	framePtr = F.prev;

	
}

function extract_items_208339(x_208341, heading_208342, items_208345, items_208345_Idx) {
			var Tmp1;

	var F={procname:"dochack.extractItems",prev:framePtr,filename:"dochack.nim",line:0};
	framePtr = F;
	BeforeRet: do {
		if ((x_208341 == null)) {
		F.line = 81;
		break BeforeRet;
		}
		
			if (!!((x_208341.heading == null))) Tmp1 = false; else {				Tmp1 = (x_208341.heading.textContent == heading_208342);			}		if (Tmp1) {
		L2: do {
			F.line = 83;
			var i_208374 = 0;
			F.line = 2728;
			var colontmp__209477 = 0;
			F.line = 83;
			colontmp__209477 = (x_208341.kids != null ? x_208341.kids.length : 0);
			F.line = 2729;
			var i_209478 = 0;
			L3: do {
				F.line = 2730;
					L4: while (true) {
					if (!(i_209478 < colontmp__209477)) break L4;
						F.line = 83;
						i_208374 = i_209478;
						F.line = 84;
						if (items_208345[items_208345_Idx] != null) { items_208345[items_208345_Idx].push(x_208341.kids[chckIndx(i_208374, 0, x_208341.kids.length+0-1)-0].heading); } else { items_208345[items_208345_Idx] = [x_208341.kids[chckIndx(i_208374, 0, x_208341.kids.length+0-1)-0].heading]; };
						F.line = 2732;
						i_209478 = addInt(i_209478, 1);
					}
			} while(false);
		} while(false);
		}
		else {
			L5: do {
				F.line = 86;
				var i_208394 = 0;
				F.line = 2728;
				var colontmp__209482 = 0;
				F.line = 86;
				colontmp__209482 = (x_208341.kids != null ? x_208341.kids.length : 0);
				F.line = 2729;
				var i_209483 = 0;
				L6: do {
					F.line = 2730;
						L7: while (true) {
						if (!(i_209483 < colontmp__209482)) break L7;
							F.line = 86;
							i_208394 = i_209483;
							F.line = 87;
							var it_208395 = x_208341.kids[chckIndx(i_208394, 0, x_208341.kids.length+0-1)-0];
							F.line = 88;
							extract_items_208339(it_208395, heading_208342, items_208345, items_208345_Idx);
							F.line = 2732;
							i_209483 = addInt(i_209483, 1);
						}
				} while(false);
			} while(false);
		}
		
	} while (false);
	framePtr = F.prev;

	
}

function tree_208020(tag_208022, kids_208024) {
	var result_208025 = null;

	var F={procname:"dochack.tree",prev:framePtr,filename:"dochack.nim",line:0};
	framePtr = F;
		F.line = 11;
		result_208025 = document.createElement(toJSStr(tag_208022));
		L1: do {
			F.line = 12;
			var k_208056 = null;
			F.line = 3;
			var i_209500 = 0;
			L2: do {
				F.line = 4;
					L3: while (true) {
					if (!(i_209500 < (kids_208024 != null ? kids_208024.length : 0))) break L3;
						F.line = 12;
						k_208056 = kids_208024[chckIndx(i_209500, 0, kids_208024.length+0-1)-0];
						F.line = 13;
						result_208025.appendChild(k_208056);
						F.line = 6;
						i_209500 = addInt(i_209500, 1);
					}
			} while(false);
		} while(false);
	framePtr = F.prev;

	return result_208025;

}

function text_208152(s_208154) {
	var result_208155 = null;

	var F={procname:"dochack.text",prev:framePtr,filename:"dochack.nim",line:0};
	framePtr = F;
		F.line = 27;
		result_208155 = document.createTextNode(s_208154);
	framePtr = F.prev;

	return result_208155;

}

function sys_fatal_59862(message_59866) {
	var F={procname:"sysFatal.sysFatal",prev:framePtr,filename:"fatal.nim",line:0};
	framePtr = F;
		F.line = 34;
		var e_60003 = null;
		F.line = 37;
		e_60003 = {m_type: NTI48850, parent: null, name: null, message: null, trace: null, raiseId: 0, up: null};
		F.line = 38;
		e_60003.message = nimCopy(null, message_59866, NTI45040);
		F.line = 39;
		raiseException(e_60003, "AssertionError");
	framePtr = F.prev;

	
}

function raise_assert_59858(msg_59860) {
	var F={procname:"assertions.raiseAssert",prev:framePtr,filename:"assertions.nim",line:0};
	framePtr = F;
		F.line = 20;
		sys_fatal_59862(msg_59860);
	framePtr = F.prev;

	
}

function failed_assert_impl_60051(msg_60053) {
	var F={procname:"assertions.failedAssertImpl",prev:framePtr,filename:"assertions.nim",line:0};
	framePtr = F;
		F.line = 27;
		raise_assert_59858(msg_60053);
	framePtr = F.prev;

	
}

function uncovered_208940(x_208942) {
			var Tmp1;
		var Tmp2;

	var result_208943 = null;

	var F={procname:"dochack.uncovered",prev:framePtr,filename:"dochack.nim",line:0};
	framePtr = F;
	BeforeRet: do {
			if (!((x_208942.kids != null ? x_208942.kids.length : 0) == 0)) Tmp1 = false; else {				Tmp1 = !((x_208942.heading == null));			}		if (Tmp1) {
		F.line = 194;
		if (!(x_208942.heading.hasOwnProperty('__karaxMarker__'))) {
		Tmp2 = x_208942;
		}
		else {
		Tmp2 = null;
		}
		
		result_208943 = Tmp2;
		break BeforeRet;
		}
		
		F.line = 195;
		result_208943 = {heading: x_208942.heading, kids: [], sortId: x_208942.sortId, doSort: x_208942.doSort};
		L3: do {
			F.line = 197;
			var i_208982 = 0;
			F.line = 2728;
			var colontmp__209512 = 0;
			F.line = 197;
			colontmp__209512 = (x_208942.kids != null ? x_208942.kids.length : 0);
			F.line = 2729;
			var i_209513 = 0;
			L4: do {
				F.line = 2730;
					L5: while (true) {
					if (!(i_209513 < colontmp__209512)) break L5;
						F.line = 197;
						i_208982 = i_209513;
						F.line = 198;
						var y_208983 = uncovered_208940(x_208942.kids[chckIndx(i_208982, 0, x_208942.kids.length+0-1)-0]);
						if (!((y_208983 == null))) {
						F.line = 199;
						if (result_208943.kids != null) { result_208943.kids.push(y_208983); } else { result_208943.kids = [y_208983]; };
						}
						
						F.line = 2732;
						i_209513 = addInt(i_209513, 1);
					}
			} while(false);
		} while(false);
		if (((result_208943.kids != null ? result_208943.kids.length : 0) == 0)) {
		F.line = 200;
		result_208943 = null;
		}
		
	} while (false);
	framePtr = F.prev;

	return result_208943;

}

function merge_tocs_209017(orig_209019, news_209020) {
	var result_209021 = null;

	var F={procname:"dochack.mergeTocs",prev:framePtr,filename:"dochack.nim",line:0};
	framePtr = F;
		F.line = 203;
		result_209021 = uncovered_208940(orig_209019);
		if ((result_209021 == null)) {
		F.line = 205;
		result_209021 = news_209020;
		}
		else {
			L1: do {
				F.line = 207;
				var i_209042 = 0;
				F.line = 2728;
				var colontmp__209506 = 0;
				F.line = 207;
				colontmp__209506 = (news_209020.kids != null ? news_209020.kids.length : 0);
				F.line = 2729;
				var i_209507 = 0;
				L2: do {
					F.line = 2730;
						L3: while (true) {
						if (!(i_209507 < colontmp__209506)) break L3;
							F.line = 207;
							i_209042 = i_209507;
							F.line = 208;
							if (result_209021.kids != null) { result_209021.kids.push(news_209020.kids[chckIndx(i_209042, 0, news_209020.kids.length+0-1)-0]); } else { result_209021.kids = [news_209020.kids[chckIndx(i_209042, 0, news_209020.kids.length+0-1)-0]]; };
							F.line = 2732;
							i_209507 = addInt(i_209507, 1);
						}
				} while(false);
			} while(false);
		}
		
	framePtr = F.prev;

	return result_209021;

}

function build_toc_209063(orig_209065, types_209067, procs_209068) {
	var result_209069 = null;

	var F={procname:"dochack.buildToc",prev:framePtr,filename:"dochack.nim",line:0};
	framePtr = F;
		F.line = 211;
		var new_stuff_209083 = {heading: null, kids: [], doSort: true, sortId: 0};
		L1: do {
			F.line = 212;
			var t_209214 = null;
			F.line = 185;
			var i_209495 = 0;
			F.line = 186;
			var l_209496 = (types_209067 != null ? types_209067.length : 0);
			L2: do {
				F.line = 187;
					L3: while (true) {
					if (!(i_209495 < l_209496)) break L3;
						F.line = 212;
						t_209214 = types_209067[chckIndx(i_209495, 0, types_209067.length+0-1)-0];
						F.line = 213;
						var c_209228 = {heading: t_209214.cloneNode(true), kids: [], doSort: true, sortId: 0};
						F.line = 214;
						t_209214.__karaxMarker__ = true;
						L4: do {
							F.line = 215;
							var p_209235 = null;
							F.line = 185;
							var i_209492 = 0;
							F.line = 186;
							var l_209493 = (procs_209068 != null ? procs_209068.length : 0);
							L5: do {
								F.line = 187;
									L6: while (true) {
									if (!(i_209492 < l_209493)) break L6;
										F.line = 215;
										p_209235 = procs_209068[chckIndx(i_209492, 0, procs_209068.length+0-1)-0];
										if (!(p_209235.hasOwnProperty('__karaxMarker__'))) {
										F.line = 217;
										var xx_209236 = p_209235.parentNode.getElementsByClassName("attachedType");
										if ((((xx_209236 != null ? xx_209236.length : 0) == 1) && (xx_209236[chckIndx(0, 0, xx_209236.length+0-1)-0].textContent == t_209214.textContent))) {
										F.line = 220;
										var q_209244 = tree_208020(makeNimstrLit("A"), [text_208152(p_209235.title)]);
										F.line = 221;
										q_209244.setAttribute("href", p_209235.getAttribute("href"));
										F.line = 222;
										if (c_209228.kids != null) { c_209228.kids.push({heading: q_209244, kids: [], sortId: 0, doSort: false}); } else { c_209228.kids = [{heading: q_209244, kids: [], sortId: 0, doSort: false}]; };
										F.line = 223;
										p_209235.__karaxMarker__ = true;
										}
										
										}
										
										F.line = 189;
										i_209492 = addInt(i_209492, 1);
										if (!(((procs_209068 != null ? procs_209068.length : 0) == l_209493))) {
										F.line = 190;
										failed_assert_impl_60051(makeNimstrLit("/Users/travis/build/nim-lang/Nim/lib/system/iterators.nim(190, 11) `len(a) == L` the length of the seq changed while iterating over it"));
										}
										
									}
							} while(false);
						} while(false);
						F.line = 224;
						if (new_stuff_209083.kids != null) { new_stuff_209083.kids.push(c_209228); } else { new_stuff_209083.kids = [c_209228]; };
						F.line = 189;
						i_209495 = addInt(i_209495, 1);
						if (!(((types_209067 != null ? types_209067.length : 0) == l_209496))) {
						F.line = 190;
						failed_assert_impl_60051(makeNimstrLit("/Users/travis/build/nim-lang/Nim/lib/system/iterators.nim(190, 11) `len(a) == L` the length of the seq changed while iterating over it"));
						}
						
					}
			} while(false);
		} while(false);
		F.line = 225;
		result_209069 = merge_tocs_209017(orig_209065, new_stuff_209083);
	framePtr = F.prev;

	return result_209069;

}

function add_208085(parent_208087, kid_208088) {
			var Tmp1;
				var Tmp2;

	var F={procname:"dochack.add",prev:framePtr,filename:"dochack.nim",line:0};
	framePtr = F;
			if (!(parent_208087.nodeName == "TR")) Tmp1 = false; else {				if ((kid_208088.nodeName == "TD")) Tmp2 = true; else {					Tmp2 = (kid_208088.nodeName == "TH");				}				Tmp1 = Tmp2;			}		if (Tmp1) {
		F.line = 18;
		var k_208089 = document.createElement("TD");
		F.line = 19;
		k_208089.appendChild(kid_208088);
		F.line = 20;
		parent_208087.appendChild(k_208089);
		}
		else {
			F.line = 22;
		parent_208087.appendChild(kid_208088);
		}
		
	framePtr = F.prev;

	
}

function set_class_208103(e_208105, value_208106) {
	var F={procname:"dochack.setClass",prev:framePtr,filename:"dochack.nim",line:0};
	framePtr = F;
		F.line = 25;
		e_208105.setAttribute("class", toJSStr(value_208106));
	framePtr = F.prev;

	
}

function to_html_208424(x_208426, is_root_208427) {
			var Tmp1;

		function HEX3Aanonymous_208467(a_208469, b_208470) {
					var Tmp1;

			var result_208471 = 0;

			var F={procname:"toHtml.:anonymous",prev:framePtr,filename:"dochack.nim",line:0};
			framePtr = F;
			BeforeRet: do {
					if (!!((a_208469.heading == null))) Tmp1 = false; else {						Tmp1 = !((b_208470.heading == null));					}				if (Tmp1) {
				F.line = 106;
				var x_208488 = a_208469.heading.textContent;
				F.line = 107;
				var y_208489 = b_208470.heading.textContent;
				if ((x_208488 < y_208489)) {
				F.line = 108;
				result_208471 = -1;
				break BeforeRet;
				}
				
				if ((y_208489 < x_208488)) {
				F.line = 109;
				result_208471 = 1;
				break BeforeRet;
				}
				
				F.line = 110;
				result_208471 = 0;
				break BeforeRet;
				}
				else {
					F.line = 113;
					result_208471 = subInt(a_208469.sortId, b_208470.sortId);
					break BeforeRet;
				}
				
			} while (false);
			framePtr = F.prev;

			return result_208471;

		}

	var result_208428 = null;

	var F={procname:"dochack.toHtml",prev:framePtr,filename:"dochack.nim",line:0};
	framePtr = F;
	BeforeRet: do {
		if ((x_208426 == null)) {
		F.line = 91;
		result_208428 = null;
		break BeforeRet;
		}
		
		if (((x_208426.kids != null ? x_208426.kids.length : 0) == 0)) {
		if ((x_208426.heading == null)) {
		F.line = 93;
		result_208428 = null;
		break BeforeRet;
		}
		
		F.line = 94;
		result_208428 = x_208426.heading.cloneNode(true);
		break BeforeRet;
		}
		
		F.line = 95;
		result_208428 = tree_208020(makeNimstrLit("DIV"), []);
			if (!!((x_208426.heading == null))) Tmp1 = false; else {				Tmp1 = !(x_208426.heading.hasOwnProperty('__karaxMarker__'));			}		if (Tmp1) {
		F.line = 97;
		add_208085(result_208428, x_208426.heading.cloneNode(true));
		}
		
		F.line = 98;
		var ul_208464 = tree_208020(makeNimstrLit("UL"), []);
		if (is_root_208427) {
		F.line = 100;
		set_class_208103(ul_208464, makeNimstrLit("simple simple-toc"));
		}
		else {
			F.line = 102;
		set_class_208103(ul_208464, makeNimstrLit("simple"));
		}
		
		if (x_208426.doSort) {
		F.line = 104;
		x_208426.kids.sort(HEX3Aanonymous_208467);
		}
		
		L2: do {
			F.line = 115;
			var k_208614 = null;
			F.line = 183;
			var colontmp__209519 = null;
			F.line = 115;
			colontmp__209519 = x_208426.kids;
			F.line = 185;
			var i_209521 = 0;
			F.line = 186;
			var l_209522 = (colontmp__209519 != null ? colontmp__209519.length : 0);
			L3: do {
				F.line = 187;
					L4: while (true) {
					if (!(i_209521 < l_209522)) break L4;
						F.line = 115;
						k_208614 = colontmp__209519[chckIndx(i_209521, 0, colontmp__209519.length+0-1)-0];
						F.line = 116;
						var y_208615 = to_html_208424(k_208614, false);
						if (!((y_208615 == null))) {
						F.line = 118;
						add_208085(ul_208464, tree_208020(makeNimstrLit("LI"), [y_208615]));
						}
						
						F.line = 189;
						i_209521 = addInt(i_209521, 1);
						if (!(((colontmp__209519 != null ? colontmp__209519.length : 0) == l_209522))) {
						F.line = 190;
						failed_assert_impl_60051(makeNimstrLit("/Users/travis/build/nim-lang/Nim/lib/system/iterators.nim(190, 11) `len(a) == L` the length of the seq changed while iterating over it"));
						}
						
					}
			} while(false);
		} while(false);
		if (!((ul_208464.childNodes.length == 0))) {
		F.line = 119;
		add_208085(result_208428, ul_208464);
		}
		
		if ((result_208428.childNodes.length == 0)) {
		F.line = 120;
		result_208428 = null;
		}
		
	} while (false);
	framePtr = F.prev;

	return result_208428;

}

function replace_by_id_208172(id_208174, new_tree_208175) {
	var F={procname:"dochack.replaceById",prev:framePtr,filename:"dochack.nim",line:0};
	framePtr = F;
		F.line = 32;
		var x_208176 = document.getElementById(id_208174);
		F.line = 33;
		x_208176.parentNode.replaceChild(new_tree_208175, x_208176);
		F.line = 34;
		new_tree_208175.id = id_208174;
	framePtr = F.prev;

	
}

function togglevis_209329(d_209331) {
	var F={procname:"dochack.togglevis",prev:framePtr,filename:"dochack.nim",line:0};
	framePtr = F;
		F.line = 230;
		    if (d_209331.style.display == 'none')
      d_209331.style.display = 'inline';
    else
      d_209331.style.display = 'none';
  
	framePtr = F.prev;

	
}

function groupBy(value_209347) {
	var F={procname:"dochack.groupBy",prev:framePtr,filename:"dochack.nim",line:0};
	framePtr = F;
		F.line = 238;
		var toc_209348 = document.getElementById("toc-list");
		if ((alternative_209315[0] == null)) {
		F.line = 240;
		var tt_209367 = {heading: null, kids: [], sortId: 0, doSort: false};
		F.line = 241;
		to_toc_208688(toc_209348, tt_209367);
		F.line = 242;
		tt_209367 = tt_209367.kids[chckIndx(0, 0, tt_209367.kids.length+0-1)-0];
		F.line = 244;
		var types_209382 = [[]];
		F.line = 245;
		var procs_209397 = [[]];
		F.line = 247;
		extract_items_208339(tt_209367, "Types", types_209382, 0);
		F.line = 248;
		extract_items_208339(tt_209367, "Procs", procs_209397, 0);
		F.line = 249;
		extract_items_208339(tt_209367, "Converters", procs_209397, 0);
		F.line = 250;
		extract_items_208339(tt_209367, "Methods", procs_209397, 0);
		F.line = 251;
		extract_items_208339(tt_209367, "Templates", procs_209397, 0);
		F.line = 252;
		extract_items_208339(tt_209367, "Macros", procs_209397, 0);
		F.line = 253;
		extract_items_208339(tt_209367, "Iterators", procs_209397, 0);
		F.line = 255;
		var ntoc_209405 = build_toc_209063(tt_209367, types_209382[0], procs_209397[0]);
		F.line = 256;
		var x_209406 = to_html_208424(ntoc_209405, true);
		F.line = 257;
		alternative_209315[0] = tree_208020(makeNimstrLit("DIV"), [x_209406]);
		}
		
		if ((value_209347 == "type")) {
		F.line = 259;
		replace_by_id_208172("tocRoot", alternative_209315[0]);
		}
		else {
			F.line = 261;
		replace_by_id_208172("tocRoot", tree_208020(makeNimstrLit("DIV"), []));
		}
		
		F.line = 262;
		togglevis_209329(document.getElementById("toc-list"));
	framePtr = F.prev;

	
}
var db_209525 = [null];
var contents_209527 = [null];
var oldtoc_209759 = [null];
var timer_209760 = [null];

function raiseRangeError() {
		var e_67441 = null;
		e_67441 = {m_type: NTI48862, parent: null, name: null, message: null, trace: null, raiseId: 0, up: null};
		e_67441.message = nimCopy(null, makeNimstrLit("value out of range"), NTI45040);
		e_67441.parent = null;
		raiseException(e_67441, "RangeError");

	
}

function nsuToLowerAsciiChar(c_196780) {
	var result_196781 = 0;

	var F={procname:"strutils.toLowerAscii",prev:framePtr,filename:"strutils.nim",line:0};
	framePtr = F;
		if ((ConstSet2[c_196780] != undefined)) {
		F.line = 222;
		result_196781 = chckRange(addInt(c_196780, 32), 0, 255);
		}
		else {
			F.line = 224;
			result_196781 = c_196780;
		}
		
	framePtr = F.prev;

	return result_196781;

}

function fuzzy_match_207070(pattern_207072, str_207073) {
							var Tmp4;
							var Tmp5;
								var Tmp6;

	var result_207077 = {Field0: 0, Field1: false};

	var F={procname:"fuzzysearch.fuzzyMatch",prev:framePtr,filename:"fuzzysearch.nim",line:0};
	framePtr = F;
		F.line = 37;
		var score_state_207078 = -100;
		F.line = 38;
		var header_matched_207079 = false;
		F.line = 39;
		var unmatched_leading_char_count_207081 = 0;
		F.line = 40;
		var consecutive_match_count_207083 = 0;
		F.line = 41;
		var str_index_207085 = 0;
		F.line = 42;
		var pat_index_207087 = 0;
		F.line = 43;
		var score_207089 = 0;
		L1: do {
			F.line = 49;
				L2: while (true) {
				if (!((str_index_207085 < (str_207073 != null ? str_207073.length : 0)) && (pat_index_207087 < (pattern_207072 != null ? pattern_207072.length : 0)))) break L2;
					L3: do {
						F.line = 51;
						var pattern_char_207095 = nsuToLowerAsciiChar(pattern_207072.charCodeAt(chckIndx(pat_index_207087, 0, pattern_207072.length+0-1)-0));
						F.line = 52;
						var str_char_207096 = nsuToLowerAsciiChar(str_207073.charCodeAt(chckIndx(str_index_207085, 0, str_207073.length+0-1)-0));
						if ((ConstSet3[pattern_char_207095] != undefined)) {
						F.line = 56;
						pat_index_207087 = addInt(pat_index_207087, 1);
						F.line = 57;
						break L3;
						}
						
						if ((ConstSet4[str_char_207096] != undefined)) {
						F.line = 59;
						str_index_207085 = addInt(str_index_207085, 1);
						F.line = 60;
						break L3;
						}
						
						if ((!(header_matched_207079) && (str_char_207096 == 58))) {
						F.line = 65;
						header_matched_207079 = true;
						F.line = 66;
						score_state_207078 = -100;
						F.line = 67;
						score_207089 = Math.trunc(Math.floor((5.0000000000000000e-01 * score_207089)));
						F.line = 68;
						pat_index_207087 = 0;
						F.line = 69;
						str_index_207085 = addInt(str_index_207085, 1);
						F.line = 70;
						break L3;
						}
						
						if ((str_char_207096 == pattern_char_207095)) {
						F.line = 73;
						switch (score_state_207078) {
						case -100:
						case 20:
							F.line = 75;
							score_state_207078 = 10;
							break;
						case 0:
							F.line = 78;
							score_state_207078 = 5;
							F.line = 78;
							score_207089 = addInt(score_207089, score_state_207078);
							break;
						case 10:
						case 5:
							F.line = 81;
							consecutive_match_count_207083 = addInt(consecutive_match_count_207083, 1);
							F.line = 82;
							score_state_207078 = 5;
							F.line = 83;
							score_207089 = addInt(score_207089, mulInt(5, consecutive_match_count_207083));
							if ((score_state_207078 == 10)) {
							F.line = 86;
							score_207089 = addInt(score_207089, 10);
							}
							
							F.line = 88;
							var on_boundary_207171 = (pat_index_207087 == (pattern_207072 != null ? (pattern_207072.length-1) : -1));
							if ((!(on_boundary_207171) && (str_index_207085 < (str_207073 != null ? (str_207073.length-1) : -1)))) {
							F.line = 91;
							var next_pattern_char_207172 = nsuToLowerAsciiChar(pattern_207072.charCodeAt(chckIndx(addInt(pat_index_207087, 1), 0, pattern_207072.length+0-1)-0));
							F.line = 92;
							var next_str_char_207173 = nsuToLowerAsciiChar(str_207073.charCodeAt(chckIndx(addInt(str_index_207085, 1), 0, str_207073.length+0-1)-0));
							F.line = 95;
							if (!!((ConstSet5[next_str_char_207173] != undefined))) Tmp4 = false; else {								Tmp4 = !((next_str_char_207173 == next_pattern_char_207172));							}							on_boundary_207171 = Tmp4;
							}
							
							if (on_boundary_207171) {
							F.line = 100;
							score_state_207078 = 20;
							F.line = 100;
							score_207089 = addInt(score_207089, score_state_207078);
							}
							
							break;
						case -1:
						case -3:
							F.line = 103;
							if (!((ConstSet6[str_207073.charCodeAt(chckIndx(subInt(str_index_207085, 1), 0, str_207073.length+0-1)-0)] != undefined))) Tmp5 = true; else {								if (!(ConstSet7[str_207073.charCodeAt(chckIndx(subInt(str_index_207085, 1), 0, str_207073.length+0-1)-0)] != undefined)) Tmp6 = false; else {									Tmp6 = (ConstSet8[str_207073.charCodeAt(chckIndx(str_index_207085, 0, str_207073.length+0-1)-0)] != undefined);								}								Tmp5 = Tmp6;							}							var is_leading_char_207211 = Tmp5;
							if (is_leading_char_207211) {
							F.line = 110;
							score_state_207078 = 10;
							}
							else {
								F.line = 114;
								score_state_207078 = 0;
								F.line = 114;
								score_207089 = addInt(score_207089, score_state_207078);
							}
							
							break;
						}
						F.line = 115;
						pat_index_207087 = addInt(pat_index_207087, 1);
						}
						else {
							F.line = 118;
							switch (score_state_207078) {
							case -100:
								F.line = 120;
								score_state_207078 = -3;
								F.line = 120;
								score_207089 = addInt(score_207089, score_state_207078);
								break;
							case 5:
								F.line = 123;
								score_state_207078 = -1;
								F.line = 123;
								score_207089 = addInt(score_207089, score_state_207078);
								F.line = 124;
								consecutive_match_count_207083 = 0;
								break;
							case -3:
								if ((unmatched_leading_char_count_207081 < 3)) {
								F.line = 128;
								score_state_207078 = -3;
								F.line = 128;
								score_207089 = addInt(score_207089, score_state_207078);
								}
								
								F.line = 129;
								unmatched_leading_char_count_207081 = addInt(unmatched_leading_char_count_207081, 1);
								break;
							default: 
								F.line = 132;
								score_state_207078 = -1;
								F.line = 132;
								score_207089 = addInt(score_207089, score_state_207078);
								break;
							}
						}
						
						F.line = 134;
						str_index_207085 = addInt(str_index_207085, 1);
					} while(false);
				}
		} while(false);
		F.line = 137;
		var colontmp__209863 = nimMax(0, score_207089);
		F.line = 138;
		var colontmp__209864 = (0 < score_207089);
		F.line = 136;
		nimCopy(result_207077, {Field0: colontmp__209863, Field1: colontmp__209864}, NTI207074);
	framePtr = F.prev;

	return result_207077;

}

function text_208120(s_208122) {
	var result_208123 = null;

	var F={procname:"dochack.text",prev:framePtr,filename:"dochack.nim",line:0};
	framePtr = F;
		F.line = 26;
		result_208123 = document.createTextNode(toJSStr(s_208122));
	framePtr = F.prev;

	return result_208123;

}

function dosearch_209544(value_209546) {

		function HEX3Aanonymous_209671(a_209680, b_209681) {
			var result_209685 = 0;

			var F={procname:"dosearch.:anonymous",prev:framePtr,filename:"dochack.nim",line:0};
			framePtr = F;
				F.line = 305;
				result_209685 = subInt(b_209681["Field1"], a_209680["Field1"]);
			framePtr = F.prev;

			return result_209685;

		}

	var result_209547 = null;

	var F={procname:"dochack.dosearch",prev:framePtr,filename:"dochack.nim",line:0};
	framePtr = F;
		if (((db_209525[0] != null ? db_209525[0].length : 0) == 0)) {
		F.line = 272;
		var stuff_209553 = null;
		F.line = 273;
		    var request = new XMLHttpRequest();
    request.open("GET", "theindex.html", false);
    request.send(null);

    var doc = document.implementation.createHTMLDocument("theindex");
    doc.documentElement.innerHTML = request.responseText;

    //parser=new DOMParser();
    //doc=parser.parseFromString("<html></html>", "text/html");

    stuff_209553 = doc.documentElement;
    
		F.line = 286;
		db_209525[0] = nimCopy(null, stuff_209553.getElementsByClassName("reference"), NTI89305);
		F.line = 287;
		contents_209527[0] = nimCopy(null, [], NTI209566);
		L1: do {
			F.line = 288;
			var ahref_209614 = null;
			F.line = 185;
			var i_209843 = 0;
			F.line = 186;
			var l_209844 = (db_209525[0] != null ? db_209525[0].length : 0);
			L2: do {
				F.line = 187;
					L3: while (true) {
					if (!(i_209843 < l_209844)) break L3;
						F.line = 288;
						ahref_209614 = db_209525[0][chckIndx(i_209843, 0, db_209525[0].length+0-1)-0];
						F.line = 289;
						if (contents_209527[0] != null) { contents_209527[0].push(ahref_209614.getAttribute("data-doc-search-tag")); } else { contents_209527[0] = [ahref_209614.getAttribute("data-doc-search-tag")]; };
						F.line = 189;
						i_209843 = addInt(i_209843, 1);
						if (!(((db_209525[0] != null ? db_209525[0].length : 0) == l_209844))) {
						F.line = 190;
						failed_assert_impl_60051(makeNimstrLit("/Users/travis/build/nim-lang/Nim/lib/system/iterators.nim(190, 11) `len(a) == L` the length of the seq changed while iterating over it"));
						}
						
					}
			} while(false);
		} while(false);
		}
		
		F.line = 290;
		var ul_209625 = tree_208020(makeNimstrLit("UL"), []);
		F.line = 291;
		result_209547 = tree_208020(makeNimstrLit("DIV"), []);
		F.line = 292;
		set_class_208103(result_209547, makeNimstrLit("search_results"));
		F.line = 293;
		var matches_209644 = [];
		L4: do {
			F.line = 294;
			var i_209657 = 0;
			F.line = 2728;
			var colontmp__209850 = 0;
			F.line = 294;
			colontmp__209850 = (db_209525[0] != null ? db_209525[0].length : 0);
			F.line = 2729;
			var i_209851 = 0;
			L5: do {
				F.line = 2730;
					L6: while (true) {
					if (!(i_209851 < colontmp__209850)) break L6;
						F.line = 294;
						i_209657 = i_209851;
						L7: do {
							F.line = 295;
							var c_209658 = contents_209527[0][chckIndx(i_209657, 0, contents_209527[0].length+0-1)-0];
							if (((c_209658 == "Examples") || (c_209658 == "PEG construction"))) {
							F.line = 300;
							break L7;
							}
							
							F.line = 301;
							var colontmp__209860 = {Field0: 0, Field1: false};
							F.line = 301;
							var score_209659 = 0;
							F.line = 301;
							var matched_209660 = false;
							F.line = 301;
							nimCopy(colontmp__209860, fuzzy_match_207070(value_209546, c_209658), NTI207074);
							F.line = 301;
							score_209659 = colontmp__209860["Field0"];
							F.line = 301;
							matched_209660 = colontmp__209860["Field1"];
							if (matched_209660) {
							F.line = 303;
							if (matches_209644 != null) { matches_209644.push({Field0: db_209525[0][chckIndx(i_209657, 0, db_209525[0].length+0-1)-0], Field1: score_209659}); } else { matches_209644 = [{Field0: db_209525[0][chckIndx(i_209657, 0, db_209525[0].length+0-1)-0], Field1: score_209659}]; };
							}
							
						} while(false);
						F.line = 2732;
						i_209851 = addInt(i_209851, 1);
					}
			} while(false);
		} while(false);
		F.line = 305;
		matches_209644.sort(HEX3Aanonymous_209671);
		L8: do {
			F.line = 306;
			var i_209724 = 0;
			F.line = 2728;
			var colontmp__209856 = 0;
			F.line = 306;
			colontmp__209856 = nimMin((matches_209644 != null ? matches_209644.length : 0), 19);
			F.line = 2729;
			var i_209857 = 0;
			L9: do {
				F.line = 2730;
					L10: while (true) {
					if (!(i_209857 < colontmp__209856)) break L10;
						F.line = 306;
						i_209724 = i_209857;
						F.line = 307;
						matches_209644[chckIndx(i_209724, 0, matches_209644.length+0-1)-0]["Field0"].innerHTML = matches_209644[chckIndx(i_209724, 0, matches_209644.length+0-1)-0]["Field0"].getAttribute("data-doc-search-tag");
						F.line = 308;
						add_208085(ul_209625, tree_208020(makeNimstrLit("LI"), [matches_209644[chckIndx(i_209724, 0, matches_209644.length+0-1)-0]["Field0"]]));
						F.line = 2732;
						i_209857 = addInt(i_209857, 1);
					}
			} while(false);
		} while(false);
		if ((ul_209625.childNodes.length == 0)) {
		F.line = 310;
		add_208085(result_209547, tree_208020(makeNimstrLit("B"), [text_208120(makeNimstrLit("no search results"))]));
		}
		else {
			F.line = 312;
			add_208085(result_209547, tree_208020(makeNimstrLit("B"), [text_208120(makeNimstrLit("search results"))]));
			F.line = 313;
			add_208085(result_209547, ul_209625);
		}
		
	framePtr = F.prev;

	return result_209547;

}

function search() {

		function wrapper_209791() {
			var F={procname:"search.wrapper",prev:framePtr,filename:"dochack.nim",line:0};
			framePtr = F;
				F.line = 320;
				var elem_209793 = document.getElementById("searchInput");
				F.line = 321;
				var value_209794 = elem_209793.value;
				if (!(((value_209794 != null ? value_209794.length : 0) == 0))) {
				if ((oldtoc_209759[0] == null)) {
				F.line = 324;
				oldtoc_209759[0] = document.getElementById("tocRoot");
				}
				
				F.line = 325;
				var results_209800 = dosearch_209544(value_209794);
				F.line = 326;
				replace_by_id_208172("tocRoot", results_209800);
				}
				else {
				if (!((oldtoc_209759[0] == null))) {
				F.line = 328;
				replace_by_id_208172("tocRoot", oldtoc_209759[0]);
				}
				}
			framePtr = F.prev;

			
		}

	var F={procname:"dochack.search",prev:framePtr,filename:"dochack.nim",line:0};
	framePtr = F;
		if (!((timer_209760[0] == null))) {
		F.line = 330;
		clearTimeout(timer_209760[0]);
		}
		
		F.line = 331;
		timer_209760[0] = setTimeout(wrapper_209791, 400);
	framePtr = F.prev;

	
}
